# 台鐵車站白名單
# 用於精準匹配車站名稱，避免誤判

stations:
  # 西部幹線 - 北段
  - 基隆
  - 三坑
  - 八堵
  - 七堵
  - 百福
  - 五堵
  - 汐止
  - 汐科
  - 南港
  - 松山
  - 臺北
  - 台北
  - 萬華
  - 板橋
  - 浮洲
  - 樹林
  - 南樹林
  - 山佳
  - 鶯歌
  - 桃園
  - 內壢
  - 中壢
  - 埔心
  - 楊梅
  - 富岡
  - 新富
  - 北湖
  - 湖口
  - 新豐
  - 竹北
  - 北新竹
  - 新竹
  - 三姓橋
  - 香山
  - 崎頂
  - 竹南
  
  # 西部幹線 - 海線
  - 談文
  - 大山
  - 後龍
  - 龍港
  - 白沙屯
  - 新埔
  - 通霄
  - 苑裡
  - 日南
  - 大甲
  - 台中港
  - 清水
  - 沙鹿
  - 龍井
  - 大肚
  - 追分
  
  # 西部幹線 - 山線
  - 造橋
  - 豐富
  - 苗栗
  - 南勢
  - 銅鑼
  - 三義
  - 泰安
  - 后里
  - 豐原
  - 栗林
  - 潭子
  - 頭家厝
  - 松竹
  - 太原
  - 精武
  - 臺中
  - 台中
  - 五權
  - 大慶
  - 烏日
  - 新烏日
  - 成功
  - 彰化
  - 花壇
  - 大村
  - 員林
  - 永靖
  - 社頭
  - 田中
  - 二水
  - 林內
  - 石榴
  - 斗六
  - 斗南
  - 石龜
  - 大林
  - 民雄
  - 嘉北
  - 嘉義
  - 水上
  - 南靖
  - 後壁
  - 新營
  - 柳營
  - 林鳳營
  - 隆田
  - 拔林
  - 善化
  - 南科
  - 新市
  - 永康
  - 大橋
  - 臺南
  - 台南
  - 保安
  - 仁德
  - 中洲
  - 大湖
  - 路竹
  - 岡山
  - 橋頭
  - 楠梓
  - 新左營
  - 左營
  - 內惟
  - 美術館
  - 鼓山
  - 三塊厝
  - 高雄
  
  # 屏東線
  - 鳳山
  - 後庄
  - 九曲堂
  - 六塊厝
  - 屏東
  - 歸來
  - 麟洛
  - 西勢
  - 竹田
  - 潮州
  - 崁頂
  - 南州
  - 鎮安
  - 林邊
  - 佳冬
  - 東海
  - 枋寮
  - 加祿
  - 內獅
  - 枋山
  
  # 南迴線
  - 枋野
  - 中央號誌
  - 古莊
  - 大武
  - 瀧溪
  - 金崙
  - 太麻里
  - 知本
  - 康樂
  - 臺東
  - 台東
  
  # 臺東線/花東線
  - 山里
  - 鹿野
  - 瑞源
  - 瑞和
  - 關山
  - 海端
  - 池上
  - 富里
  - 東竹
  - 東里
  - 玉里
  - 三民
  - 瑞穗
  - 富源
  - 大富
  - 光復
  - 萬榮
  - 鳳林
  - 南平
  - 林榮新光
  - 豐田
  - 壽豐
  - 平和
  - 志學
  - 吉安
  - 花蓮
  - 北埔
  - 景美
  - 新城
  - 崇德
  - 和仁
  - 和平
  - 漢本
  - 武塔
  - 南澳
  - 東澳
  - 永樂
  - 蘇澳新
  - 蘇澳
  - 冬山
  - 羅東
  - 中里
  - 二結
  - 宜蘭
  - 四城
  - 礁溪
  - 頂埔
  - 頭城
  - 外澳
  - 龜山
  - 大溪
  - 大里
  - 石城
  - 福隆
  - 貢寮
  - 雙溪
  - 牡丹
  - 三貂嶺
  - 猴硐
  - 瑞芳
  - 四腳亭
  - 暖暖
  
  # 平溪線
  - 大華
  - 十分
  - 望古
  - 嶺腳
  - 平溪
  - 菁桐
  
  # 內灣線
  - 北新竹
  - 千甲
  - 新莊
  - 竹中
  - 上員
  - 榮華
  - 竹東
  - 橫山
  - 九讚頭
  - 合興
  - 富貴
  - 內灣
  
  # 六家線
  - 六家
  
  # 集集線
  - 源泉
  - 濁水
  - 龍泉
  - 集集
  - 水里
  - 車埕
  
  # 沙崙線
  - 長榮大學
  - 沙崙
